default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['API_HOST'] %>
  port: <%= ENV['API_PORT'] %>
  username: <%= ENV['API_USERNAME'] %>
  password: <%= ENV['API_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  variables:
    statement_timeout: <%= ENV.fetch("API_DATABASE_TIMEOUT") { 10000 } %>

development:
  <<: *default
  database: <%= "#{ENV['API_DATABASE']}_development" %>

test:
  <<: *default
  database: <%= "#{ENV['API_DATABASE']}_test" %>

production:
  <<: *default
  database: <%= ENV['API_DATABASE'] %>
